### ISSUE TITLE
Plugin not compatible with Gradle 4.2

### ISSUE THREAD

**Issue by marceloverdijk** [xvik/gradle-quality-plugin#3]
Using this plugin with latest Gradle `4.2` gives the following error:

```
Caused by: java.lang.NoClassDefFoundError: org/gradle/reporting/DurationFormatter
        at ru.vyarus.gradle.plugin.quality.QualityPlugin.<clinit>(QualityPlugin.groovy:58)
        at org.gradle.api.internal.DependencyInjectingInstantiator.newInstance(DependencyInjectingInstantiator.java:81)
        at org.gradle.api.internal.plugins.DefaultPluginManager.instantiatePlugin(DefaultPluginManager.java:72)
        ... 112 more

```

It seems `org.gradle.reporting.DurationFormatter` has been moved to `org.gradle.internal.logging.format.DurationFormatter`.

**Comment by xvik** [comment]
New version [released](https://github.com/xvik/gradle-quality-plugin/releases/tag/2.4.0)

Thank you for the info!

**Comment by marceloverdijk** [comment]
👍
